### ISSUE TITLE
Failed to download Kippo example logs

### ISSUE THREAD

**Issue by studiawan** [desaster/kippo#199] opened 2016-02-17 01:33 UTC
I tried to download some logs in Demo section of Readme.md and unfortunately I got this following error:

502 Bad Gateway
nginx/1.6.2

Please check the website http://kippo.rpg.fi for its availability. Thanks!

**Comment by s4wny** [comment] 2016-03-12 22:33
Duplicate of #193 and #186

**Comment by desaster** [comment] 2021-01-20 20:15
fixed links with a browser based playlog https://github.com/desaster/playlog-web

**Closed by desaster** 2021-01-20 20:15 UTC
