### ISSUE TITLE
kippo.pid permission issue

### ISSUE THREAD

**Issue by BhautikRamani** [desaster/kippo#225] opened 2017-11-27 10:38 UTC
I got this error when I try to start kippo..

/opt/kippo$ ./start.sh 
twistd (the Twisted daemon) 15.2.0
Copyright (c) 2001-2015 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
An error has occurred: '[Errno 13] Permission denied: '/opt/kippo/kippo.pid''
Please look at log file for more information.

How can I fix it ?

**Comment by desaster** [comment] 2017-11-27 10:41
duplicate of #224

**Closed by desaster** 2017-11-27 10:41 UTC
