### ISSUE TITLE
kippo.pid permissions 

### ISSUE THREAD

**Issue by BhautikRamani** [desaster/kippo#224] opened 2017-11-27 10:33 UTC
when I try to start kippo I got this error, 

/opt/kippo$ ./start.sh 
twistd (the Twisted daemon) 15.2.0
Copyright (c) 2001-2015 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
An error has occurred: '[Errno 13] Permission denied: '/opt/kippo/kippo.pid''
Please look at log file for more information.

How can I fix it?

**Comment by desaster** [comment] 2017-11-27 10:35
looks like an user error - no permissions to the specified directory. The twisted version is also wrong, so this is probably not done according to wiki.

I'm closing this as it's not a bug.

**Closed by desaster** 2017-11-27 10:35 UTC
